services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
     ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
     ME_CONFIG_BASICAUTH: "false"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    restart: always
    ports:
      - 8000:8000 # Change this if your Python app uses a different port
    environment:
      DATABASE_URL: mongodb://mongo:27017/rag
    depends_on:
      - mongo
